
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels: { app: worker }
  template:
    metadata: { labels: { app: worker } }
    spec:
      containers:
        - name: worker
          image: {{ .Values.image.worker }}
          ports: [{containerPort: 9100}]
