
apiVersion: apps/v1
kind: Deployment
metadata: { name: api }
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
      - name: api
        image: {{ .Values.image.api }}
        env:
          - name: DATABASE_URL
            value: postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.db }}
          - name: REDIS_URL
            value: redis://redis:6379/0
        ports: [{ containerPort: 80 }]
        readinessProbe: { httpGet: { path: /healthz, port: 80 }, initialDelaySeconds: 5, periodSeconds: 5 }
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits: { cpu: "300m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata: { name: api }
spec:
  selector: { app: api }
  ports: [{ port: 80, targetPort: 80 }]
